services:
  mongodb:
    image: mongo
    container_name: mongo_db
    ports:
      - 27017:27017
    volumes:
      - mongo:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=slo
      - MONGO_INITDB_ROOT_PASSWORD=slo
  mongo-express:
    image: mongo-express
    container_name: mongo_express
    depends_on:
      - mongodb
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=slo
      - ME_CONFIG_MONGODB_ADMINPASSWORD=slo
      - ME_CONFIG_MONGODB_SERVER=mongo_db
volumes:
  mongo: {}